name: ci-golang-workflow
on: 
  pull_request:
    branches:
      - develop
      - main
permissions:
      deployments: write
jobs:
  check-application:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.15
      - run: go test
      - run: go run math.go
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Build
      run: go build -v math

    - name: Test
      run: go test -v

  deploy-dev:
    runs-on: ubuntu-latest
    environment:
      name: dev
    needs: build
    steps:
    - name: Run an one-line script
      run: npm start
  deploy-prd:
    runs-on: ubuntu-latest
    environment:
      name: prd
    needs: deploy-dev
    steps:
    - name: Run an one-line script
      run: npm start
